name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Set Mail
        run: git config --global user.email "tzachbonfil@gmail.com"
      - name: Set Username
        run: git config --global user.name "tzachbon"
      - name: Set Token
        run: git remote set-url origin https://6c9fad914aac92113506d34b55442cd8b2e445cb@github.com/tzachbon/portfolio.git
      - name: Deploy
        run: npm run deploy
